name:                obskura
version:             0.1.0.0
github:              "githubuser/gardspirito"
license:             BSD3
maintainer:          "guardspirit@protonmail.com"
copyright:           "2021 obscurative.ru"

dependencies:
- rio >= 0.1
- base >= 4
- template-haskell >= 2
- network >= 3
- yesod >= 1
- yesod-core >= 1
- yesod-form >= 1
- persistent >= 2
- persistent-mongoDB >= 2
- mongoDB >= 2
- text >= 1
- bytestring >= 0.10
- filepath >= 1.4
- json >= 0.4
- containers >= 0.6
- bifunctors >= 5
- dns >= 4
- mime-mail >= 0.5
- which >= 0.2
- monad-logger >= 0.3

executables:
  obskura:
    main:                Apl.hs
    source-dirs:         servil
    ghc-options:
    - -Wall
    - -O2
    - -fllvm
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -XNoImplicitPrelude
    - -XDataKinds
    - -XDerivingStrategies
    - -XFlexibleInstances
    - -XGADTs
    - -XGeneralisedNewtypeDeriving
    - -XMultiParamTypeClasses
    - -XOverloadedStrings
    - -XQuasiQuotes
    - -XStandaloneDeriving
    - -XTemplateHaskell
    - -XTypeFamilies
    - -XUndecidableInstances
    - -XViewPatterns
    - -XOverloadedStrings
    - -XMonadComprehensions
    - -XTupleSections

