resolver: nightly-2022-02-05

packages:
- .

allow-newer: true

nix:
  enable: true
  pure: false
  packages: [zlib, llvmPackages_12.llvm]

extra-deps:
- which-0.2@sha256:db82ca7d83d64cce8ad579756f02d27c5bd289806ee02474726f7fafb87318e8,858
